/* ソース選択GUI
*/
call main;
endmacro $$return;

main:
	execmacro currentmacrodirectory+"\\internal\\gui.mac", currentmacrodirectory+"\\sources";
	##num=split($$contents,getresultex(-1),"\n");
	if(##num==1){
		$$sources=$$contents[0];
		$$options="";
	}else if(##num==2){
		$$sources=$$contents[0];
		$$options=$$contents[1];
	}else{
		return "0";
	}
	execmacro currentmacrodirectory+"\\internal\\main.mac",currentmacrodirectory,$$sources,$$options;
	return getresultex(-1);
