/*

*/

#g_dll_ohtorii_tools=val(getarg(30));
$label=getarg(0);
$arg1=getarg(1);
$arg2=getarg(2);
$arg3=getarg(3);
$arg4=getarg(4);
$arg5=getarg(5);
call $label, $arg1, $arg2, $arg3, $arg4, $arg5;
endmacro $$return;



////////////////////////////////////////////////////////////////////////////
//	Request.
////////////////////////////////////////////////////////////////////////////

do_action:
	$$action=$$1;
	call $$action;
	return $$return;
