/* file_mru
*/

#g_dll_ohtorii_tools=val(getarg(0));
$label=getarg(1);
$arg=getarg(2);
call $label, $arg;
endmacro $$return;



get_property:
	return R"([property]
name=file_mru
'default_action=hidemaru_filer
base_kind=file

[action.remove]
function=remove
description=ファイル履歴から削除する
is_quit=false
is_multi_selectable=true
)";


do_action:
	$$action=$$1;
	call $$action;
	return $$return;


remove:
	debuginfo 1;
	debuginfo "[file_mru] remove";
	return "1";

