/* window
*/

#g_dll_ohtorii_tools=val(getarg(0));
$label=getarg(1);
$arg=getarg(2);
call $label, $arg;
endmacro $$return;



get_property:
	return R"([property]
name=window
default_action=preview

[action.preview]
function=preview
description=Preview window.
is_quit=false
is_multi_selectable=false
)";


do_action:
	$$action=$$1;
	call $$action;
	return $$return;

preview:
	//ウインドウを切り替える
	//少し待つ
	//元のウインドウに切り替える
	return "1";
