/*アクション候補
*/

#g_dll_ohtorii_tools=val(getarg(0));
$label=getarg(1);
$arg=getarg(2);
call $label, $arg;
endmacro $$return;


get_property:
	return R"([property]
name=action
description=candidates from unity action
default_kind=action
candidate_type=function
)";

gather_candidates:
	##context=val($$1);
	
	//
	//選択されたソースから候補を生成する
	//
	##ret=dllfuncw(#g_dll_ohtorii_tools, "KindsGenerateCandidates", ##context);
	if(##ret==false){
		return "0";
	}
	return "1";
