/*
*/
$g_root_macro_directory =getstaticvariable("$unity.root_macro_directory", 1);

call LoadDll;
endmacro str(##return);


LoadDll:
	//ohtorii_toolsを読み込む
	if(platform&0x00080000){
		##dll_ohtorii_tools = loaddll($g_root_macro_directory + "\\dll\\ohtorii_tools_x64.dll");
	}else{
		##dll_ohtorii_tools = loaddll($g_root_macro_directory + "\\dll\\ohtorii_tools_x86.dll");
	}
	if (##dll_ohtorii_tools==0) {
		message "dll\\ohtorii_tools.dllのロードに失敗しました";
		return 0;
	}
	return ##dll_ohtorii_tools;
