name: "Coverity Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  analyze:
    runs-on: windows-latest

    env:
      COVERITY_SCAN_BRANCH_PATTERN:     "${{ github.ref}}"
      COVERITY_SCAN_NOTIFICATION_EMAIL: "example@example.com"
      COVERITY_SCAN_PROJECT_NAME:       "${{ github.repository }}"
      # Set in repo settings -> secrets -> repository secrets
      COVERITY_SCAN_TOKEN:              "${{ secrets.COVERITY_SCAN_TOKEN }}"
      CURRENT_REF:                      "${{ github.ref }}"
      MY_NAME: hoge


    steps:
      #- name: Repository checkout
      #  uses: actions/checkout@v2
    
      - name: Download coverity scan build tool
        shell: cmd
        run: |
          echo wget -q https://scan.coverity.com/download/cxx/linux64 \
            --post-data "token=%COVERITY_SCAN_TOKEN%&project=ohtorii/unity" \
            -O cov-analysis-win64.tar.gz
          mkdir cov-analysis-win64
          tar xzf cov-analysis-win64.tar.gz --strip 1 -C cov-analysis-win64

