name: "Coverity Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  analyze:
    runs-on: windows-latest

    env:
      COVERITY_SCAN_BRANCH_PATTERN:     "${{ github.ref}}"
      COVERITY_SCAN_NOTIFICATION_EMAIL: "example@example.com"
      COVERITY_SCAN_PROJECT_NAME:       "${{ github.repository }}"
      # Set in repo settings -> secrets -> repository secrets
      COVERITY_SCAN_TOKEN:              "${{ secrets.COVERITY_SCAN_TOKEN }}"
      CURRENT_REF:                      "${{ github.ref }}"
      MY_NAME: hoge


    steps:
      - name: Check cmd
        shell: cmd
        run: echo cmd ok
      
      - name: Check pwsh
        shell: pwsh
        run: echo pwsh ok
        
      - name: Check bash
        shell: bash
        run: echo bash ok
          
      #- name: Repository checkout
      #  uses: actions/checkout@v2
    
      - name: Download coverity scan build tool
        shell: cmd
        run: |
          echo token1=%COVERITY_SCAN_TOKEN%
          echo token2=$COVERITY_SCAN_TOKEN
          echo MY_NAME=$MY_NAME
          echo MY_NAME=%MY_NAME%

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a one-line script2
        run: echo "Hello, world!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: SET
        shell: cmd
        run: set
